In [1]:
#Data-analytiikan ohjelmointikielet
#3. Datan muokkaus ja siivoamine
#R-esimerkit


#Ladataan tilastokeskuksen data. Haetaan data JSON-muodossa suoraan Tilastokeskuksen PXWeb-palvelun tarjoaman
#rajapinnan kautta. Asennetaan tätä varten pxweb-paketti. 

#install.packages("pxweb")

library(pxweb)

url = "https://pxdata.stat.fi:443/PxWeb/api/v1/fi/StatFin/aku/statfin_aku_pxt_12dz.px"


data <- pxweb_get(url)

#Tulostetaan sisältö

str(data)

pxweb 0.17.0: R tools for the PX-WEB API.
https://github.com/ropengov/pxweb

List of 2
 $ title    : chr "Aikuiskoulutukseen osallistuminen (ml. työhön tai ammattiin liittyvä, henkilöstökoulutus sekä muu kuin työhön l"| __truncated__
 $ variables:List of 3
  ..$ :List of 6
  .. ..$ code       : chr "Vuosi"
  .. ..$ text       : chr "Vuosi"
  .. ..$ values     : chr [1:7] "1990" "1995" "2000" "2006" ...
  .. ..$ valueTexts : chr [1:7] "1990" "1995" "2000" "2006" ...
  .. ..$ time       : logi TRUE
  .. ..$ elimination: logi FALSE
  ..$ :List of 6
  .. ..$ code       : chr "Ikä"
  .. ..$ text       : chr "Ikä"
  .. ..$ values     : chr [1:6] "SSS" "18-24" "25-34" "35-44" ...
  .. ..$ valueTexts : chr [1:6] "Yhteensä" "18 - 24" "25 - 34" "35 - 44" ...
  .. ..$ elimination: logi TRUE
  .. ..$ time       : logi FALSE
  ..$ :List of 6
  .. ..$ code       : chr "Tiedot"
  .. ..$ text       : chr "Tiedot"
  .. ..$ values     : chr [1:8] "akuo_lkm" "akuo_pros" "tyoo_lkm" "tyoo_pros" ...
  .. ..$ valueTexts : chr [1:8] "Aikuiskoulutukseen osallistuneet, lkm" "Aikuiskoulutukseen osallistuneet, %" "Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm" "Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %" ...
  .. ..$ elimination: logi FALSE
  .. ..$ time       : logi FALSE
 - attr(*, "class")= chr [1:2] "pxweb_metadata" "list"

In [2]:
#Tulostuksesta nähdään käytetyt koodit. Tehdään kysely, jossa nämä kaikki ovat mukana. 
#Tämä kysely kohdistetaan sitten JSON-tiedostoon. Haetaan tiedostosta siis kaikki mahdollinen. 

query <- list(
  "Vuosi" = "*",
  "Ikä" = "*",
  "Tiedot" = "*"
)

data <- pxweb_get_data(url, query = query)

print(data)

   Vuosi      Ikä Aikuiskoulutukseen osallistuneet, lkm
1   1990 Yhteensä                               1526457
2   1990  18 - 24                                204552
3   1990  25 - 34                                416027
4   1990  35 - 44                                481846
5   1990  45 - 54                                291068
6   1990  55 - 64                                132963
7   1995 Yhteensä                               1555554
8   1995  18 - 24                                183534
9   1995  25 - 34                                381866
10  1995  35 - 44                                425144
11  1995  45 - 54                                404908
12  1995  55 - 64                                160102
13  2000 Yhteensä                               1754057
14  2000  18 - 24                                225413
15  2000  25 - 34                                409527
16  2000  35 - 44                                474888
17  2000  45 - 54                                463366
18  2000  55 - 64                                180863
19  2006 Yhteensä                               1706728
20  2006  18 - 24                                198693
21  2006  25 - 34                                373428
22  2006  35 - 44                                441924
23  2006  45 - 54                                430683
24  2006  55 - 64                                262001
25  2012 Yhteensä                               1715520
26  2012  18 - 24                                197995
27  2012  25 - 34                                394207
28  2012  35 - 44                                415339
29  2012  45 - 54                                432854
30  2012  55 - 64                                275125
31  2017 Yhteensä                               1584069
32  2017  18 - 24                                177849
33  2017  25 - 34                                395268
34  2017  35 - 44                                372384
35  2017  45 - 54                                377242
36  2017  55 - 64                                261327
37  2022 Yhteensä                               1452840
38  2022  18 - 24                                178091
39  2022  25 - 34                                291667
40  2022  35 - 44                                362093
41  2022  45 - 54                                341665
42  2022  55 - 64                                279325
   Aikuiskoulutukseen osallistuneet, %
1                                   47
2                                   43
3                                   55
4                                   57
5                                   48
6                                   25
7                                   48
8                                   42
9                                   53
10                                  54
11                                  54
12                                  31
13                                  54
14                                  49
15                                  62
16                                  62
17                                  56
18                                  33
19                                  52
20                                  43
21                                  58
22                                  61
23                                  56
24                                  37
25                                  52
26                                  42
27                                  58
28                                  63
29                                  58
30                                  36
31                                  48
32                                  38
33                                  57
34                                  56
35                                  52
36                                  35
37                                  47
38                                  44
39                                  48
40                                  53
41                                  54
42                                  38
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1                                                                1092182
2                                                                  97831
3                                                                 329104
4                                                                 373050
5                                                                 234914
6                                                                  57283
7                                                                1032090
8                                                                  50555
9                                                                 260675
10                                                                325990
11                                                                317436
12                                                                 77434
13                                                               1231175
14                                                                 77432
15                                                                298999
16                                                                388827
17                                                                379929
18                                                                 85988
19                                                               1266735
20                                                                 69120
21                                                                274747
22                                                                374510
23                                                                375150
24                                                                173208
25                                                               1316903
26                                                                 86655
27                                                                287470
28                                                                354718
29                                                                374717
30                                                                213344
31                                                               1191489
32                                                                 68176
33                                                                287581
34                                                                314841
35                                                                318425
36                                                                202465
37                                                               1081451
38                                                                 36380
39                                                                221542
40                                                                303634
41                                                                296806
42                                                                223090
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1                                                                   44
2                                                                   36
3                                                                   50
4                                                                   48
5                                                                   44
6                                                                   27
7                                                                   43
8                                                                   27
9                                                                   44
10                                                                  45
11                                                                  47
12                                                                  33
13                                                                  51
14                                                                  41
15                                                                  56
16                                                                  56
17                                                                  52
18                                                                  34
19                                                                  51
20                                                                  36
21                                                                  54
22                                                                  57
23                                                                  54
24                                                                  40
25                                                                  54
26                                                                  48
27                                                                  57
28                                                                  61
29                                                                  55
30                                                                  42
31                                                                  48
32                                                                  40
33                                                                  55
34                                                                  53
35                                                                  49
36                                                                  36
37                                                                  46
38                                                                  30
39                                                                  48
40                                                                  50
41                                                                  52
42                                                                  38
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
1                                                                         968734
2                                                                          82445
3                                                                         285334
4                                                                         338924
5                                                                         209508
6                                                                          52524
7                                                                         830830
8                                                                          37360
9                                                                         204640
10                                                                        264282
11                                                                        261089
12                                                                         63460
13                                                                       1004515
14                                                                         62174
15                                                                        241792
16                                                                        322034
17                                                                        307692
18                                                                         70823
19                                                                       1107670
20                                                                         68919
21                                                                        242893
22                                                                        317475
23                                                                        323426
24                                                                        154957
25                                                                       1137285
26                                                                         74049
27                                                                        244715
28                                                                        310112
29                                                                        320955
30                                                                        187453
31                                                                       1004137
32                                                                         47385
33                                                                        243614
34                                                                        251803
35                                                                        278187
36                                                                        183148
37                                                                       1019683
38                                                                         34476
39                                                                        211472
40                                                                        287854
41                                                                        282554
42                                                                        203326
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
1                                                                           47
2                                                                           34
3                                                                           50
4                                                                           52
5                                                                           48
6                                                                           37
7                                                                           52
8                                                                           33
9                                                                           50
10                                                                          53
11                                                                          57
12                                                                          51
13                                                                          56
14                                                                          46
15                                                                          57
16                                                                          61
17                                                                          57
18                                                                          47
19                                                                          57
20                                                                          46
21                                                                          57
22                                                                          61
23                                                                          60
24                                                                          52
25                                                                          59
26                                                                          52
27                                                                          61
28                                                                          66
29                                                                          59
30                                                                          51
31                                                                          53
32                                                                          48
33                                                                          59
34                                                                          55
35                                                                          56
36                                                                          44
37                                                                          54
38                                                                          40
39                                                                          55
40                                                                          57
41                                                                          60
42                                                                          45
   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1                                                                             545297
2                                                                              49301
3                                                                             127314
4                                                                             172371
5                                                                             111111
6                                                                              85202
7                                                                             518648
8                                                                              36170
9                                                                             126507
10                                                                            147087
11                                                                            131040
12                                                                             77844
13                                                                            511857
14                                                                             39338
15                                                                            121145
16                                                                            122872
17                                                                            139374
18                                                                             89128
19                                                                            520378
20                                                                             44530
21                                                                            107223
22                                                                            121623
23                                                                            132888
24                                                                            114114
25                                                                            519266
26                                                                             38365
27                                                                            127861
28                                                                            117970
29                                                                            126913
30                                                                            108158
31                                                                            385562
32                                                                             21819

In [3]:
#Muunnetaan data tibbleksi (kehittyneempi dataframe, vastaa Julian dataframea)

df <- as.data.frame(data, column.name.type = "text", variable.value.type = "text")

df

   Vuosi Ikä      Aikuiskoulutukseen osallistuneet, lkm
1  1990  Yhteensä 1526457
2  1990  18 - 24   204552
3  1990  25 - 34   416027
4  1990  35 - 44   481846
5  1990  45 - 54   291068
6  1990  55 - 64   132963
7  1995  Yhteensä 1555554
8  1995  18 - 24   183534
9  1995  25 - 34   381866
10 1995  35 - 44   425144
11 1995  45 - 54   404908
12 1995  55 - 64   160102
13 2000  Yhteensä 1754057
14 2000  18 - 24   225413
15 2000  25 - 34   409527
16 2000  35 - 44   474888
17 2000  45 - 54   463366
18 2000  55 - 64   180863
19 2006  Yhteensä 1706728
20 2006  18 - 24   198693
21 2006  25 - 34   373428
22 2006  35 - 44   441924
23 2006  45 - 54   430683
24 2006  55 - 64   262001
25 2012  Yhteensä 1715520
26 2012  18 - 24   197995
27 2012  25 - 34   394207
28 2012  35 - 44   415339
29 2012  45 - 54   432854
30 2012  55 - 64   275125
31 2017  Yhteensä 1584069
32 2017  18 - 24   177849
33 2017  25 - 34   395268
34 2017  35 - 44   372384
35 2017  45 - 54   377242
36 2017  55 - 64   261327
37 2022  Yhteensä 1452840
38 2022  18 - 24   178091
39 2022  25 - 34   291667
40 2022  35 - 44   362093
41 2022  45 - 54   341665
42 2022  55 - 64   279325
   Aikuiskoulutukseen osallistuneet, %
1  47
2  43
3  55
4  57
5  48
6  25
7  48
8  42
9  53
10 54
11 54
12 31
13 54
14 49
15 62
16 62
17 56
18 33
19 52
20 43
21 58
22 61
23 56
24 37
25 52
26 42
27 58
28 63
29 58
30 36
31 48
32 38
33 57
34 56
35 52
36 35
37 47
38 44
39 48
40 53
41 54
42 38
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1  1092182
2    97831
3   329104
4   373050
5   234914
6    57283
7  1032090
8    50555
9   260675
10  325990
11  317436
12   77434
13 1231175
14   77432
15  298999
16  388827
17  379929
18   85988
19 1266735
20   69120
21  274747
22  374510
23  375150
24  173208
25 1316903
26   86655
27  287470
28  354718
29  374717
30  213344
31 1191489
32   68176
33  287581
34  314841
35  318425
36  202465
37 1081451
38   36380
39  221542
40  303634
41  296806
42  223090
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1  44
2  36
3  50
4  48
5  44
6  27
7  43
8  27
9  44
10 45
11 47
12 33
13 51
14 41
15 56
16 56
17 52
18 34
19 51
20 36
21 54
22 57
23 54
24 40
25 54
26 48
27 57
28 61
29 55
30 42
31 48
32 40
33 55
34 53
35 49
36 36
37 46
38 30
39 48
40 50
41 52
42 38
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
1   968734
2    82445
3   285334
4   338924
5   209508
6    52524
7   830830
8    37360
9   204640
10  264282
11  261089
12   63460
13 1004515
14   62174
15  241792
16  322034
17  307692
18   70823
19 1107670
20   68919
21  242893
22  317475
23  323426
24  154957
25 1137285
26   74049
27  244715
28  310112
29  320955
30  187453
31 1004137
32   47385
33  243614
34  251803
35  278187
36  183148
37 1019683
38   34476
39  211472
40  287854
41  282554
42  203326
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
1  47
2  34
3  50
4  52
5  48
6  37
7  52
8  33
9  50
10 53
11 57
12 51
13 56
14 46
15 57
16 61
17 57
18 47
19 57
20 46
21 57
22 61
23 60
24 52
25 59
26 52
27 61
28 66
29 59
30 51
31 53
32 48
33 59
34 55
35 56
36 44
37 54
38 40
39 55
40 57
41 60
42 45
   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1  545297
2   49301
3  127314
4  172371
5  111111
6   85202
7  518648
8   36170
9  126507
10 147087
11 131040
12  77844
13 511857
14  39338
15 121145
16 122872
17 139374
18  89128
19 520378
20  44530
21 107223
22 121623
23 132888
24 114114
25 519266
26  38365
27 127861
28 117970
29 126913
30 108158
31 385562
32  21819
33  75927
34 100754
35  95400
36  91661
37 378530
38  23050
39  72531
40 103609
41  97701
42  81638
   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1  18
2  17
3  18
4  21
5  18
6  16
7  18
8  18
9  19
10 19
11 17
12 15
13 18
14 19
15 20
16 17
17 17
18 16
19 18
20 21
21 19
22 17
23 17
24 16
25 18
26 20
27 22
28 19
29 17
30 14
31 14
32 12
33 13
34 16
35 14
36 12
37 14
38 16
39 15
40 16
41 16
42 11

In [4]:
#Nyt huomataan, että pxweb-kirjasto ymmärtää rakenteen semantiikan, kun taas Julia lukee vain raakadatan. Tämän takia arvot ovat oikein
#ja Juliassa tehtyä muokkausta ei tarvita. Näin ollen R on monesti parempi valinta PxWebin tarkasteluun.

#Lisäksi huomataan, että tuloksissa on mukana Yhteensä-arvoja. Suodatetaan nämä pois. Lisäksi

library(dplyr)

df <- df |> filter(Ikä != "Yhteensä")

df

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

   Vuosi Ikä     Aikuiskoulutukseen osallistuneet, lkm
1  1990  18 - 24 204552
2  1990  25 - 34 416027
3  1990  35 - 44 481846
4  1990  45 - 54 291068
5  1990  55 - 64 132963
6  1995  18 - 24 183534
7  1995  25 - 34 381866
8  1995  35 - 44 425144
9  1995  45 - 54 404908
10 1995  55 - 64 160102
11 2000  18 - 24 225413
12 2000  25 - 34 409527
13 2000  35 - 44 474888
14 2000  45 - 54 463366
15 2000  55 - 64 180863
16 2006  18 - 24 198693
17 2006  25 - 34 373428
18 2006  35 - 44 441924
19 2006  45 - 54 430683
20 2006  55 - 64 262001
21 2012  18 - 24 197995
22 2012  25 - 34 394207
23 2012  35 - 44 415339
24 2012  45 - 54 432854
25 2012  55 - 64 275125
26 2017  18 - 24 177849
27 2017  25 - 34 395268
28 2017  35 - 44 372384
29 2017  45 - 54 377242
30 2017  55 - 64 261327
31 2022  18 - 24 178091
32 2022  25 - 34 291667
33 2022  35 - 44 362093
34 2022  45 - 54 341665
35 2022  55 - 64 279325
   Aikuiskoulutukseen osallistuneet, %
1  43
2  55
3  57
4  48
5  25
6  42
7  53
8  54
9  54
10 31
11 49
12 62
13 62
14 56
15 33
16 43
17 58
18 61
19 56
20 37
21 42
22 58
23 63
24 58
25 36
26 38
27 57
28 56
29 52
30 35
31 44
32 48
33 53
34 54
35 38
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1   97831
2  329104
3  373050
4  234914
5   57283
6   50555
7  260675
8  325990
9  317436
10  77434
11  77432
12 298999
13 388827
14 379929
15  85988
16  69120
17 274747
18 374510
19 375150
20 173208
21  86655
22 287470
23 354718
24 374717
25 213344
26  68176
27 287581
28 314841
29 318425
30 202465
31  36380
32 221542
33 303634
34 296806
35 223090
   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1  36
2  50
3  48
4  44
5  27
6  27
7  44
8  45
9  47
10 33
11 41
12 56
13 56
14 52
15 34
16 36
17 54
18 57
19 54
20 40
21 48
22 57
23 61
24 55
25 42
26 40
27 55
28 53
29 49
30 36
31 30
32 48
33 50
34 52
35 38
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
1   82445
2  285334
3  338924
4  209508
5   52524
6   37360
7  204640
8  264282
9  261089
10  63460
11  62174
12 241792
13 322034
14 307692
15  70823
16  68919
17 242893
18 317475
19 323426
20 154957
21  74049
22 244715
23 310112
24 320955
25 187453
26  47385
27 243614
28 251803
29 278187
30 183148
31  34476
32 211472
33 287854
34 282554
35 203326
   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
1  34
2  50
3  52
4  48
5  37
6  33
7  50
8  53
9  57
10 51
11 46
12 57
13 61
14 57
15 47
16 46
17 57
18 61
19 60
20 52
21 52
22 61
23 66
24 59
25 51
26 48
27 59
28 55
29 56
30 44
31 40
32 55
33 57
34 60
35 45
   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
1   49301
2  127314
3  172371
4  111111
5   85202
6   36170
7  126507
8  147087
9  131040
10  77844
11  39338
12 121145
13 122872
14 139374
15  89128
16  44530
17 107223
18 121623
19 132888
20 114114
21  38365
22 127861
23 117970
24 126913
25 108158
26  21819
27  75927
28 100754
29  95400
30  91661
31  23050
32  72531
33 103609
34  97701
35  81638
   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1  17
2  18
3  21
4  18
5  16
6  18
7  19
8  19
9  17
10 15
11 19
12 20
13 17
14 17
15 16
16 21
17 19
18 17
19 17
20 16
21 20
22 22
23 19
24 17
25 14
26 12
27 13
28 16
29 14
30 12
31 16
32 15
33 16
34 16
35 11

In [5]:
#Nyt huomataan, että dataframe on oletuksena lyhyessä (leveässä) muodossa toisin kuin Juliassa. Muutetaan se pitkäksi. 

library(tidyr)

df_pitka <- pivot_longer(
  df,
  cols = -c(Vuosi, Ikä),   # kaikki muut sarakkeet paitsi nämä venytetään
  names_to = "Tiedot",     # uusi sarake sarakenimistä
  values_to = "Arvo"       # uusi sarake arvoista
)

df_pitka


#Funktio pivot_wider() muuttaa pitkän datan tarvittaessa lyhyeksi.

    Vuosi Ikä
1   1990  18 - 24
2   1990  18 - 24
3   1990  18 - 24
4   1990  18 - 24
5   1990  18 - 24
6   1990  18 - 24
7   1990  18 - 24
8   1990  18 - 24
9   1990  25 - 34
10  1990  25 - 34
11  1990  25 - 34
12  1990  25 - 34
13  1990  25 - 34
14  1990  25 - 34
15  1990  25 - 34
16  1990  25 - 34
17  1990  35 - 44
18  1990  35 - 44
19  1990  35 - 44
20  1990  35 - 44
21  1990  35 - 44
22  1990  35 - 44
23  1990  35 - 44
24  1990  35 - 44
25  1990  45 - 54
26  1990  45 - 54
27  1990  45 - 54
28  1990  45 - 54
29  1990  45 - 54
30  1990  45 - 54
... ...   ...
251 2022  25 - 34
252 2022  25 - 34
253 2022  25 - 34
254 2022  25 - 34
255 2022  25 - 34
256 2022  25 - 34
257 2022  35 - 44
258 2022  35 - 44
259 2022  35 - 44
260 2022  35 - 44
261 2022  35 - 44
262 2022  35 - 44
263 2022  35 - 44
264 2022  35 - 44
265 2022  45 - 54
266 2022  45 - 54
267 2022  45 - 54
268 2022  45 - 54
269 2022  45 - 54
270 2022  45 - 54
271 2022  45 - 54
272 2022  45 - 54
273 2022  55 - 64
274 2022  55 - 64
275 2022  55 - 64
276 2022  55 - 64
277 2022  55 - 64
278 2022  55 - 64
279 2022  55 - 64
280 2022  55 - 64
    Tiedot
1   Aikuiskoulutukseen osallistuneet, lkm
2   Aikuiskoulutukseen osallistuneet, %
3   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
4   Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
5   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
6   Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
7   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
8   Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
9   Aikuiskoulutukseen osallistuneet, lkm
10  Aikuiskoulutukseen osallistuneet, %
11  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
12  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
13  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
14  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
15  Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
16  Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
17  Aikuiskoulutukseen osallistuneet, lkm
18  Aikuiskoulutukseen osallistuneet, %
19  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
20  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
21  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
22  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
23  Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
24  Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
25  Aikuiskoulutukseen osallistuneet, lkm
26  Aikuiskoulutukseen osallistuneet, %
27  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
28  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
29  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
30  Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
... ...
251 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
252 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
253 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
254 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
255 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
256 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
257 Aikuiskoulutukseen osallistuneet, lkm
258 Aikuiskoulutukseen osallistuneet, %
259 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
260 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
261 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
262 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
263 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
264 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
265 Aikuiskoulutukseen osallistuneet, lkm
266 Aikuiskoulutukseen osallistuneet, %
267 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
268 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
269 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
270 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
271 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
272 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
273 Aikuiskoulutukseen osallistuneet, lkm
274 Aikuiskoulutukseen osallistuneet, %
275 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
276 Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
277 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, lkm
278 Työnantajan tukemaan koulutukseen (henkilöstökoulutukseen) osallistuneet, %
279 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, lkm
280 Muuhun kuin työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
    Arvo
1   204552
2       43
3    97831
4       36
5    82445
6       34
7    49301
8       17
9   416027
10      55
11  329104
12      50
13  285334
14      50
15  127314
16      18
17  481846
18      57
19  373050
20      48
21  338924
22      52
23  172371
24      21
25  291068
26      48
27  234914
28      44
29  209508
30      48
... ...
251 221542
252     48
253 211472
254     55
255  72531
256     15
257 362093
258     53
259 303634
260     50
261 287854
262     57
263 103609
264     16
265 341665
266     54
267 296806
268     52
269 282554
270     60
271  97701
272     16
273 279325
274     38
275 223090
276     38
277 203326
278     45
279  81638
280     11

In [6]:
#Analysoidaan dataa seuraavaksi tekemällä Pivot-taulukko, jossa osa datasta on suodatettu pois. 

df_suod <- df_pitka %>%
  filter(
    Vuosi == "2022",
    Tiedot %in% c(
      "Aikuiskoulutukseen osallistuneet, %",
      "Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %",
      "Aikuiskoulutukseen osallistuneet, lkm"
    )
  ) %>%

select(Vuosi, Ikä, Tiedot, Arvo) %>%
  pivot_wider(
    names_from = Tiedot,
    values_from = Arvo
  )
  
#Tehtävä: Käytä tekoälyä ja selvitä yksityiskohtaisesti mitä yllä olevassa koodissa tapahtuu. Tämän ymmärtäminen on tärkeää. 
df_suod

  Vuosi Ikä     Aikuiskoulutukseen osallistuneet, lkm
1 2022  18 - 24 178091
2 2022  25 - 34 291667
3 2022  35 - 44 362093
4 2022  45 - 54 341665
5 2022  55 - 64 279325
  Aikuiskoulutukseen osallistuneet, %
1 44
2 48
3 53
4 54
5 38
  Työhön tai ammattiin liittyvään aikuiskoulutukseen osallistuneet, %
1 30
2 48
3 50
4 52
5 38

In [7]:
#Lasketaan lopuksi montako henkilöä osallistui aikuiskoulutukseen vuonna 2022. Laskeminen olisi onnistunut myös
#ilman tyyppimuunnosta, koska kaikki sarakkeen arvot ovat kokonaislukuja. Jos näin ei olisi, niin laskeminen antaisi
#virheilmoituksen. Myös desimaaliluvut kelpaisivat. 

sum(df_suod$`Aikuiskoulutukseen osallistuneet, lkm`, na.rm = TRUE) #Argumentti na.rm = TRUE varmistaa, että puuttuvia arvoja ei oteta mukaan.

[1] 1452841